name: tests

on:
  push:
    branches:
      - main
  pull_request:

  jobs:
    vitest:
      name: API Tests
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install deps
        run: npm install
      - name: Run app
      - name: Build app
        run: npm run build
      - name: Run app
        run: npm run start
      - name: Run tests
        run: npm run test
